### ISSUE TITLE
Comment .gifv links fail to load

### ISSUE THREAD

**Issue by angelbouzo** [Kennyc1012/OpenImgur#38]
When opening a .gifv link in the comment section, the VideoView activity crashes.

![Galaxy Note Edge](https://cloud.githubusercontent.com/assets/10983681/6701905/69fa1098-ccf9-11e4-8a3c-671dac05b762.png)

**Comment by Kennyc1012** [comment]
Is this happening on all .gifv links? That usually happens if the video is corrupted due to a bad download.

**Comment by angelbouzo** [comment]
I have only seen it happen to .gifv links from comments. It shows fine the first time, however when you click on the image(to maybe download it or share) the fullscreen VideoView opens and gives this error.

**Comment by Kennyc1012** [comment]
Can you provide detailed steps on how to reproduce, and logs if you are able to pull them. I am currently able to reproduce this bug.

**Comment by angelbouzo** [comment]
Open a image/gallery/album and go to the comments. In the comments look for a .gifv url, click on it. The image shows up fine, click on that image. After that the error should show up. I tested this on both the Play store version of the app and the one here. 

    21329-21329/com.kennyc.open.imgur E/ViewRootImpl﹕ sendUserActionEvent() mView == null
    03-19 13:12:28.119  21329-21329/com.kennyc.open.imgur E/MediaPlayer-JNI﹕ QCMediaPlayer     mediaplayer NOT present
    03-19 13:12:28.139      330-330/? E/tmiMPEG2TSExtractor﹕ SnifftmiMPEG2TS @LINE=1380
    03-19 13:12:28.139      330-330/? E/MediaPlayerService﹕ error: -2147483648
    03-19 13:12:28.139  21329-21329/com.kennyc.open.imgur E/MediaPlayer﹕ Unable to create media   player

**Comment by angelbouzo** [comment]
Another log I found that is related: 

    03-19 13:53:05.340  32748-32748/com.kennyc.open.imgur W/VideoView﹕ Unable to open content: /data/data/com.kennyc.open.imgur/cache/video_cache/1s4yx0hj1wzo3mk00mho7n2hq.mp4
    java.io.IOException: setDataSourceFD failed.: status=0x80000000
            at android.media.MediaPlayer._setDataSource(Native Method)
            at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1423)
            at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1407)
            at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1341)
            at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1279)
            at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1006)
            at com.kenny.openimgur.ui.VideoView.openVideo(VideoView.java:247)
            at com.kenny.openimgur.ui.VideoView.access$1500(VideoView.java:51)
            at com.kenny.openimgur.ui.VideoView$6.surfaceCreated(VideoView.java:462)
            at android.view.SurfaceView.updateWindow(SurfaceView.java:601)
            at android.view.SurfaceView.access$000(SurfaceView.java:94)
            at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:184)
            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:895)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2270)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1316)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6804)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
            at android.view.Choreographer.doCallbacks(Choreographer.java:613)
            at android.view.Choreographer.doFrame(Choreographer.java:583)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5752)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Jawnnypoo** [comment]
Are you on a Samsung device? What version of Android are you running? I cannot reproduce this on a Nexus 7 (5.0)

**Comment by angelbouzo** [comment]
I'm using a Samsung Note Edge running Android 4.4.4.

**Comment by angelbouzo** [comment]
Also, tested this on a Moto G.

**Comment by Kennyc1012** [comment]
Could be an issue where the video is still being accessed in the popup fragment and when it goes to open in full screen, it can't open it because it's still being accessed. I'll put something together hopefully by tonight or tomorrow and send you a test apk to see if it resolves it.

**Comment by angelbouzo** [comment]
Alright. I'm messing with the code too. I'll let you know if I find anything.

**Comment by Jawnnypoo** [comment]
For me, I can only reproduce this on the Play Store version on a device running 4.4.4. Not sure if that is related though

**Comment by angelbouzo** [comment]
I fix it. The problem was in the video cache. I'll make a pull request.

**Comment by angelbouzo** [comment]
I just pulled from the development branch. It seems that it isn't effected.

**Comment by Kennyc1012** [comment]
I did some work on handling links better that isn't currently in master, that probably fixes the issue which is why I can't replicate it (I am on development). This has brought to my attention that the VideoCache can run into potentially, so I will still be keeping this open and will be making a fix.
