### ISSUE TITLE
Crash BaseGridFragment 

### ISSUE THREAD

**Issue by Kennyc1012** [Kennyc1012/OpenImgur#68]
java.lang.IllegalStateException: Fragment GalleryFragment{43475be8} not attached to Activity
       at android.app.Fragment.getResources(Fragment.java:770)
       at com.kenny.openimgur.fragments.BaseGridFragment$2.run(BaseGridFragment.java:370)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5314)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678)
       at dalvik.system.NativeStart.main(NativeStart.java)

@Jawnnypoo Noticed a few instance of this crash popping up with the addition of P2R. Has to do with the method [padRefreshBelowView](https://github.com/Kennyc1012/OpenImgur/blob/master/src/main/java/com/kenny/openimgur/fragments/BaseGridFragment.java#L366).

**Comment by Jawnnypoo** [comment]
Hmm yeah, that makes sense. Should probably wrap that onPreDraw runnable in a if (fragment.isAdded()) call. I'll get it done
